{% set name = "interlap" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: 31e4f30c54b067c4939049f5d8131ae5e2fa682ec71aa56f89c0e5b900806ec9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - interlap

about:
  summary: 'interlap: fast, simple interval overlap testing'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  home: http://brentp.github.io/interlap
  doc_url: https://brentp.github.io/interlap
  dev_url: https://github.com/brentp/interlap
  description: |
    InterLap: simple, fast interval overlap testing
    InterLap is >20 times faster than doing a naive search (see: https://brentp.github.io/interlap/benchmark.html)
    with **no memory overhead** because it operates on a sorted list. It is pure python and has no dependencies.

    It uses binary search and a knowledge of the longest observed interval to quickly query datasets with 100's of thousands of intervals.

extra:
  recipe-maintainers:
    - jenzopr
