travis:
  secure:
    BINSTAR_TOKEN: jOKqoreEbMVPhnzuRFl9JmommnOzqNtRgBi0GUSSUcY8jrRPN83ng5B66DCTxH+KElasBlcES992zoVAsTEKUHhopxCcBrzAP9IyPHR370OcDHkPWQWsZNiMum27cjP36gJuskaoTFmxstMLOrX+PkeXrr/8/Zi1UUfEg07bcdYCQKZIoGFugA+0y6yzIwpke3f5JTvvmsq4f69yn9qJ0f+niSt//24zTvK+MzxCwzY1md/zfU37o5QPEICgU1g0ufJTUMjDVGV9IR6j9mQVENPLWKwFx4B5ABB55aKEn2ZqEiHF4051eMVapUbvCVKqRd0GV639YKsFiLTutDvTJbWEDgcX34VihBqayjGORiHXmoqdxpUtSPqZ/XqzpBHBaQngJxxyi0Tmi+lp4S59ROiQcwptA1bxFIAr5RO/fXUeOQXMK0CvZJzN3QAsKaDM1oF5tIsS4jQziz8ohsZur3XQXUMIiLWkIJ2h99DUE7zpvz20Xlfz3MQZjcBm1/D7iuQYOI4jhzU/oEqc3AcbaGRvCTzGcX9MmPd4txLiJRHIxQjxQQw04/4qwoJO6Ewjp5C7OqZtVGnXm7vdfdHq5TjmUMhwXo2DkDDWG5+u2VvClcgA9OqVjMQMHI8AI8nhhQwRvxYqjvSX1krotsDa56fWh0nsyLfDh1pofx4yg0k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
