travis:
  secure:
    BINSTAR_TOKEN: CYtJP4ulqflJmjKLOmogz41a1Huh2LCdnwe4DCT32x5/Ci4SlgDKcJM1+vKSkzV3q8yAM8Yv8JZiKRvDzi2GUlaQg2ry8+OFYr/oSDW7fGYKDYgqGao/DorAra5O9AL/XVbwQP8VGCydpQd7D8MWQC1lefCXEVxV2m4eU7jRhSS7u7aqlzuMWCEcIj+mOEVWonynbIFiKw5Zib/dgNIYrTkeP3T5EAeK/sPx6xuRkiIEHsEMCsq0mjRds1rAyNDKpyRzHBQfAadqhoBq1nO525nPZy6WbzI+mlIHPr+eG8bhlKWPbv0zAeb7InF4zlGBJsHU27bJsECQrPA9LrKWOcfqDSGzkxxPlJSFY42HcByh+w5GQvvu1l4hBoBX/kAc4JtEljZrHf+SnvuwwTogsYEo4XrdWcw9Um0jr3HInynILOvkTmwI0hAx3uatTjV/Yxnp6T3nCKf6ivwxchQ1c4DdaBF9xo44BJzSMytp7bDfNUuXx5612zCiaVQ0Dp0wCU1xibUOvIOBTkMxM3cn79Sx0WviABg6slBij8jfynR38urx95PlcFtTf8Y9RPXekvrVMZv8geNi74VI5+MUfiiwKiVD1d44HH/93cXQACG0AL2U9CJ/FB0vFDHlbj9Gwxt3fh5npG81Vc3kjDkJKtsGmT1QnzlCCUh0hTLMoD4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
